on:
  push:
    branches: [ dev-1.12.2 ]
  pull_request:
    branches: [ dev-1.12.2 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
      - name: Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
