on:
  push:
    branches: [ dev-1.12.2 ]
  pull_request:
    branches: [ dev-1.12.2 ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
