name: RemoteTrigger

on:
  push:
    branches:
    - dev-1.12.2
    
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: dev-1.12.2
    - name: check
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        push-branch: 'dev-1.12.2'
        commit-message: 'Trigger CI'
        force-add: 'true'
        name: ROMVoid95
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: jenkins
      uses: enflo/jenkins-action@master
      with:
        url: 'https://jenkins.romvoid.dev/'
        token: ${{ secrets.JENKINS_TOKEN }}
        job: 'job/Interstellar-Exoplanets'
